### ISSUE TITLE
Derived_params.csv companion masses are printed incorrectly

### ISSUE THREAD

**Issue by MNGuenther** [MNGuenther/allesfitter#33]
In the derived_params.csv table, the M_earth and M_jup values are printed incorrectly.
(All other values, especially the fitted ones, are correct.)

**Comment by MNGuenther** [comment]
This was a minor bug introduced by a recent update in 1.2.4, where allesfitter's deriver.py introduced separate mass calculations to differ double-line binaries (fitting for K and q) and single-line binaries / exoplanets (fitting for K only). The parameter q is set to 1 by default and ignored for single-line binaries / exoplanets. The if-else statement to differ those cases was incorrect and q=1 was accidentally used to compute the masses for single-line binaries / exoplanets, meaning the printed result was merely the host mass. All fixed now.

**Comment by gdransfield** [comment]
Hi Max!

For me this problem persists, despite having the most recent version installed. I'm running a 3-planet fit and all derived masses come up as the stellar mass. 

I've installed the most recent version from pypi and compared the files with what's currently on Github and it's a match, Not sure what to do!

Cheers,
George 

![ns_derived_corner](https://user-images.githubusercontent.com/56828869/130785410-c1a06e06-093b-45d3-9869-b83f510f4dd0.jpg)
